apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slow-gecko-go-prod
  namespace: rhtap
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/slow-gecko-go/overlays/prod
    repoURL: https://github.com/rhtap-hub/slow-gecko-go-gitops.git
    targetRevision: main
  destination:
    namespace: oc-ci-e2e-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
