apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: slow-gecko-go
  janus-idp.io/tekton: slow-gecko-go
  backstage.io/kubernetes-id: slow-gecko-go
  backstage.io/kubernetes-namespace: oc-ci-e2e 
  app.kubernetes.io/part-of: slow-gecko-go
resources: 
- deployment.yaml
- route.yaml
- service.yaml
